name: Frontend CI

on:
  push:
    branches:
      - feature/**
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  WORKDIR: ./frontend

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKDIR }}

      - name: Run Lint
        run: npm run lint
        working-directory: ${{ env.WORKDIR }}

      - name: Run Unit Tests + Coverage
        run: npm run test -- --coverage
        working-directory: ${{ env.WORKDIR }}